const STANDARD_SAFE = '#2f5596';
const STANDARD_TIMELY = '#1a71c0';
const STANDARD_INDIVIDUALISED = '#3bb1ef';
const STANDARD_HEALTHY = '#53b151';
const STANDARD_DIGNIFIED = '#f79733';
const STANDARD_EFFECTIVE = '#7035a2';
const STANDARD_STAFF = '#ec462e';

const colors = {
  STANDARD_SAFE,
  STANDARD_TIMELY,
  STANDARD_INDIVIDUALISED,
  STANDARD_HEALTHY,
  STANDARD_DIGNIFIED,
  STANDARD_EFFECTIVE,
  STANDARD_STAFF,
};

export default colors;
